services:
  db:
    image: mysql:8.0
    restart: always
    container_name: mysql-todo
    environment:
      MYSQL_ROOT_PASSWORD: db_root_pass
      MYSQL_DATABASE: todo
      MYSQL_USER: todouser
      MYSQL_PASSWORD: todopass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - todo-network

volumes:
  db-data:

networks:
  todo-network:
